export const cards = [
    {id: 0, name: 'Zephyria', checked: false},
    {id: 1, name: 'Celestria', checked: false},
    {id: 2, name: 'Elysium', checked: false},
    // {id: 3, name: 'Hyperion', checked: false},
    // {id: 4, name: 'Nova Prime', checked: false},
    // {id: 5, name: 'Lyrae-7', checked: false},
    // {id: 6, name: 'Zenitha', checked: false},
    // {id: 7, name: 'Nebulon', checked: false},
    // {id: 8, name: 'Aetheris', checked: false},
    // {id: 9, name: 'Sylvaria', checked: false},
    // {id: 10, name: 'Orionis', checked: false},
    // {id: 11, name: 'Aquaterra', checked: false},
    // {id: 12, name: 'Gaia-X', checked: false},
    // {id: 13, name: 'Solaris', checked: false},
    // {id: 14, name: 'Seraphis', checked: false},
    // {id: 15, name: 'Chronos', checked: false},
    // {id: 16, name: 'Terra Nova', checked: false},
    // {id: 17, name: 'Astra Prime', checked: false},
    // {id: 18, name: 'Arcadia', checked: false},
    // {id: 19, name: 'Pulsaris', checked: false},
    // {id: 20, name: 'Phobosia', checked: false},
    // {id: 21, name: 'Veridion', checked: false},
    // {id: 22, name: 'Elektra', checked: false},
    // {id: 23, name: 'Stellaris', checked: false},
    // {id: 24, name: 'Avalon', checked: false},
    // {id: 25, name: 'Zirconia', checked: false},
    // {id: 26, name: 'Astralis', checked: false},
    // {id: 27, name: 'Titanis', checked: false},
    // {id: 28, name: 'Vanguard', checked: false},
    // {id: 29, name: 'Xenora', checked: false},
    // {id: 30, name: 'Nebulae', checked: false}
]