export const Planets = [
    {id: 0, name: 'Zephyria'},
    {id: 1, name: 'Celestria'},
    {id: 2, name: 'Elysium'},
    {id: 3, name: 'Hyperion'},
    {id: 4, name: 'Nova Prime'},
    {id: 5, name: 'Lyrae-7'},
    {id: 6, name: 'Zenitha'},
    {id: 7, name: 'Nebulon'},
    {id: 8, name: 'Aetheris'},
    {id: 9, name: 'Sylvaria'},
    {id: 10, name: 'Orionis'},
    {id: 11, name: 'Aquaterra'},
    {id: 12, name: 'Gaia-X'},
    {id: 13, name: 'Solaris'},
    {id: 14, name: 'Seraphis'},
    {id: 15, name: 'Chronos'},
    {id: 16, name: 'Terra Nova'},
    {id: 17, name: 'Astra Prime'},
    {id: 18, name: 'Arcadia'},
    {id: 19, name: 'Pulsaris'},
    {id: 20, name: 'Phobosia'},
    {id: 21, name: 'Veridion'},
    {id: 22, name: 'Elektra'},
    {id: 23, name: 'Stellaris'},
    {id: 24, name: 'Avalon'},
    {id: 25, name: 'Zirconia'},
    {id: 26, name: 'Astralis'},
    {id: 27, name: 'Titanis'},
    {id: 28, name: 'Vanguard'},
    {id: 29, name: 'Xenora'},
    {id: 30, name: 'Nebulae'}
]